### PR TITLE
Change autoposting delay time

### LINKED ISSUE #81: Autoposting interval timing issues
## issue 
Using the auto-posting section, my bot is getting rate-limited on every other post.
image
This seems to be caused by the posts not being spaced a minute apart 
on further inspection of the issue, I believe this is caused by my hosting machine taking a long time to send the post request

On further inspection of the issue, it seems to be caused by [this line](https://github.com/labdiscord/statcord.js/blob/63898d6d2a69aef0a76484756d83cccf77bf4d77/src/Statcord.js#L217), which auto-posts every minute

this could potentially be solved by changing it to use `setTimeout`, as it is used with error handling [in this line](https://github.com/labdiscord/statcord.js/blob/63898d6d2a69aef0a76484756d83cccf77bf4d77/src/Statcord.js#L172)

### PR DESCRIPTION
**Pull request by wrac4242**
resolves #81

### CODE REVIEW

**Comment by wrac4242** [comment]
hey, uh, any updates?

**Review by Solixity — APPROVED** [review]

**Comment by Solixity** [comment]
We're checking to see if there's any other workarounds we can apply server-side before we hit client-side. Give us an additional 72 hours and if there's no news, I'll more than likely go ahead and merge this PR.

**Comment by wrac4242** [comment]
There is potentially another way, where the post function is automatically recalled at the end of the function with setTimeout after the request has been sent, and the response has been processed, ensuring that the process only runs at least after the ratelimit

**Comment by wrac4242** [comment]
I believe it has been longer than 72 hours, have any new ideas been considered?

**Comment by wrac4242** [comment]
https://github.com/labdiscord/statcord.js/issues/81#issuecomment-1094303223
seems to fix it on slower devices

**Review by anishanne — APPROVED** [review]
lgtm

**Pull request merged**
