### PR TITLE
Fix discord.js version check to get user count

### PR DESCRIPTION
**Pull request by Gorniaky**
This PR fixes the bug mentioned in #84

### CODE REVIEW

**Review by rodycouto — APPROVED** [review]
I've tried this fixed and it work fine.
Please, pull this commit.

**Comment by Codeize** [comment]
tested locally, works fine.

**Review by Codeize — APPROVED** [review]

**Comment by Solixity** [comment]
Stop approving PRs!!!!!!!!!!!!

I'm kidding, thank y'all for approving, I'll merge tonight.

**Review by rodycouto — APPROVED** [review]
This work perfectly!

**Comment by Codeize** [comment]
Any ETA on the merge?

CC: @ThatRedPandaDev

**Comment by rodycouto** [comment]
We need this merge.

**Review by Solixity — APPROVED** [review]

**Comment by Solixity** [comment]
Approved and merged. Update statcord.js whenever possible.

**Comment by Codeize** [comment]
Appreciate it, maybe an announcement in the support server would reach the people who need to know too :)

**Pull request merged**
